version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
      - image: circleci/postgres:11.5

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.setup
      - run: mix test
